### ISSUE TITLE
EMS Hud Info

### ISSUE THREAD

**Issue by Unfellowed** [LaoYutang/l4d2-server#1]
Hello! Which line should I edit to change this height (arrow)? Thank you!
![Screenshot (48)](https://github.com/LaoYutang/l4d2-server/assets/115072518/c6d287ee-4abe-4be3-9206-200ac1d6f638)

**Comment by LaoYutang** [comment]
you can edit cfg/sourcemod/l4d2_emshud_info.cfg for hub plugin,but without this height.
